import { readFile, writeFile } from 'node:fs/promises';

const wasmFile = new URL('../dist/terrain.wasm', import.meta.url);
const outputFile = new URL('../terrain-inline.js', import.meta.url);
const encodedWasm = (await readFile(wasmFile)).toString('base64');

await writeFile(
    outputFile,
    `// Generated by npm run build. Keeps the WASM build launchable from file:// URLs.\nwindow.GForceTerrainWasmBase64 = '${encodedWasm}';\n`
);
